CREATE TABLE IF NOT EXISTS `form_ASCVD_Risk_Calculators` (
id bigint(20) NOT NULL auto_increment,
date datetime default NULL,
pid bigint(20) default NULL,
user varchar(255) default NULL,
groupname varchar(255) default NULL,
authorized tinyint(4) default NULL,
activity tinyint(4) default NULL,
age TEXT,
sex TEXT,
race TEXT,
sbp TEXT,
bmi TEXT,
hdl TEXT,
tot_chol TEXT,
bp_med TEXT,
smoking TEXT,
diabetes TEXT,
lipid_med TEXT,
fh_heartattack TEXT,
cac TEXT,
10y_accaha TEXT,
10y_frs TEXT,
10y_frs_simple TEXT,
10y_frs_hard TEXT,
10y_mesa TEXT,
10y_mesa_cac TEXT,

PRIMARY KEY (id)
) ENGINE=InnoDB;
